spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Account?useSSL=false&serverTimezone=UTC
    username: root  # ????MySQL??????
    password: N9752mbkTze # ????MySQL??????
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  servlet:
    context-path: /account


